### ISSUE TITLE
Can I list this on tabnine.com?

### ISSUE THREAD

**Issue by zxqfl** [tbodt/deoplete-tabnine#1]
As a secondary option, so Vim will still exist, but there will also be a Vim (Deoplete) option.

The reason I don't want to replace the existing Vim client completely is that I think installing Deoplete could be a barrier for users who don't use package managers.

**Comment by tbodt** [comment]
Sure, go ahead!

(though if you want to throw in a free tabnine license I wouldn't mind... 😉)

**Comment by zxqfl** [comment]
Oh of course, I mixed you up with someone else and thought I had already given you one. What's your email? You can send it to me at jacobbfjackson@gmail.com if you don't want to post it here.

@Shougo The offer stands for you too :)

**Comment by tbodt** [comment]
@zxqfl My email's on my github profile :)

**Comment by zxqfl** [comment]
Sent!

**Comment by Shougo** [comment]
My email is displayed on my github account page, too,

**Comment by zxqfl** [comment]
Sent

**Comment by Shougo** [comment]
Thank you!
