### ISSUE TITLE
Does not replace the word starting with number.

### ISSUE THREAD

**Issue by zgqq** [tbodt/deoplete-tabnine#13]
For example,  typing "20", then selecting item "2018" according to completion items;  instead of "2018", the result is "202018".

**Comment by Shougo** [comment]
Please test https://github.com/tbodt/deoplete-tabnine/pull/12.
It may fix your problem.

**Comment by Shougo** [comment]
Reproduced.  I will fix it.

**Comment by Shougo** [comment]
`self.input_pattern = r'\S*$'` causes the problem.

**Comment by Shougo** [comment]
I think `self.input_pattern = r'[^\w\s]$'` is better.

@tbodt Ping.

`r'\S*$'` matches `20|` position.
So it breaks the complete position.

**Comment by tbodt** [comment]
`[^\w\s]` seems like it would trigger the completion only when you type special characters like `.`. But wouldn't you want it to trigger even on letters, so if you're in the middle of typing a word it can still give you completions?

**Comment by Shougo** [comment]
Hm...  I will add `get_complete_position()` in #12.

**Comment by Shougo** [comment]
> But wouldn't you want it to trigger even on letters, so if you're in the middle of typing a word it can still give you completions?

It can give the completion.  Because, it matches `min_pattern_length`.

**Comment by Shougo** [comment]
I have added another get_complete_position() in #12.

https://github.com/tbodt/deoplete-tabnine/pull/12

It fixes the problem.  But needs test.
