### ISSUE TITLE
Not getting semantic completion with solargraph

### ISSUE THREAD

**Issue by iovis** [tbodt/deoplete-tabnine#14]
Hi, I'm guessing I'm doing something wrong.

Today I installed the plugin via `Plug` and opened a ruby file. I can see `[TN]` showing up in deoplete but it's not `solargraph` data. `autozimu/LanguageClient-neovim` seems to get solargraph data, so that should not be the issue. Maybe I'm missing some configuration steps?

I haven't purchased a license yet —and honestly I have no idea where I'd have to put it—, but given that there was a free tier I thought it'd work.

This is my Deoplete config:
```vim
let g:deoplete#auto_complete_delay = 100
let g:deoplete#enable_at_startup = 1

call deoplete#custom#source('ultisnips', 'matchers', ['matcher_fuzzy'])
call deoplete#custom#source('ultisnips', 'rank', 1000)
call deoplete#custom#source('syntax', 'rank', 100)
```

**Comment by Shougo** [comment]
It works for me.
But you need to enable semantic completion in the buffer.

Please read this.
https://tabnine.com/semantic

**Comment by iovis** [comment]
Thanks for the quick response!

How do I enable that? I already tried running `TabNine::sem` as a command in vim and it doesn't exist...

**Comment by Shougo** [comment]
It seems the behavior changed after deoplete-tabnine uses protocol 1.0.
Please wait.

https://github.com/zxqfl/TabNine/issues/30#issuecomment-447788335

**Comment by Shougo** [comment]
Oh, it seems client side's bug.
Please wait.

**Comment by Shougo** [comment]
@iovis9 Please test https://github.com/tbodt/deoplete-tabnine/pull/15.

**Comment by gunar** [comment]
How can I be sure `deoplete-tabnine` is getting semantic completion for typescript? I can't seem to run `TabNine::sem` anywhere. #dumbquestion #thankyou

**Comment by Shougo** [comment]
> How can I be sure deoplete-tabnine is getting semantic completion for typescript?

It works for me.

> I can't seem to run TabNine::sem anywhere. #dumbquestion #thankyou

It works for me.

**Comment by jaydorsey** [comment]
> How do I enable that? I already tried running `TabNine::sem` as a command in vim and it doesn't exist...

It's not a vim command, you just type it as regular text (insert mode) on any page or buffer you've opened in vim
