### ISSUE TITLE
 Is this a successful operation?

### ISSUE THREAD

**Issue by glepnir** [tbodt/deoplete-tabnine#16]
I am not sure if I have successfully run it. After using it for a while, I feel it is just a simple completion plugin? I don't feel special, I am sorry that I don't know tabnine very well. Can you simply introduce and configure it, I mainly use it to write go
![3333](https://user-images.githubusercontent.com/41671631/50375588-b8cfb280-063a-11e9-887b-c02908cb564a.png)
![44444](https://user-images.githubusercontent.com/41671631/50375603-fdf3e480-063a-11e9-95d4-9a917fa9977f.png)

**Comment by glepnir** [comment]
@Shougo Please help me

**Comment by Shougo** [comment]
Your tabnine already works.

You should read tabnine documentation in official page to configure.
deoplete-tabnine just use tabnine as completion source.

**Comment by glepnir** [comment]
> 你的tabnine已经有效了。
> 
> 您应该阅读官方页面中的tabnine文档进行配置。
> deoplete-tabnine只是使用tabnine作为完成源。

It turned out to be the case. I read the official documentation of tabnine. There is very little information about tabnine in China. Forgive me for not being very good at English, so I didn't configure tabnine. Just added deoplete-tanine. So I have not experienced the power of tabnine. I will study how to use tabnine, thank you very much for your help.
