### ISSUE TITLE
Error while trying to activate license

### ISSUE THREAD

**Issue by yome** [tbodt/deoplete-tabnine#2]
While trying to use this and entering the key to activate my license I'm getting the error message:
"Couldn't write your registration key to disk due to the following error: No such file or directory (os error 2)".

I don't have time to dig into this right now but I'll try to give it a go later today.

**Comment by Shougo** [comment]
It seems tabnine's issue.
You should ask it on this.

https://github.com/zxqfl/TabNine/issues

**Comment by yome** [comment]
I've found the issue, it's very simple. Tabnine's binary expect the folder with the executable to be called "binaries" but right now it's named "bin". I'll submit a PR that solves this.

**Comment by tbodt** [comment]
Fixed by #3.
