### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hissssst** [tbodt/deoplete-tabnine#24]
![22Jul19_115527](https://user-images.githubusercontent.com/37012324/61619911-72960c80-ac78-11e9-9124-1b544c5b1bd8.png)

Received this error while I was editing `elixir` file in insert mode.

Setup: 
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```

Default `deoplete-tabnine` and `deoplete` config,
installed via `neovim-plug`

**Comment by Shougo** [comment]
Tabnine process seems crashed.
Please restart neovim.

**Comment by hissssst** [comment]
Anyway, it would be nice to have an error wrapper for this case. I might be able to do this - just ask :)

**Comment by tbodt** [comment]
It looks like you got unlucky and TabNine died between line 132 and 135. Feel free to add a handler for this case :)

**Comment by Shougo** [comment]
I have added the error handler.

@hissssst Please test it.

**Comment by hissssst** [comment]
@Shougo I've copied the PR, works nice. I think it would be better to catch `BrokenPipeError` though

**Comment by Shougo** [comment]
OK.  I have changed it to `BrokenPipeError`
