### ISSUE TITLE
Opening parens are not being closed automatically

### ISSUE THREAD

**Issue by dkvasnicka** [tbodt/deoplete-tabnine#26]
TabNine introduced a feature when it closes parentheses it opens in a completion suggestion. However this plugin does not honor that and no parens are being closed

See https://github.com/zxqfl/TabNine/commit/bca744fa0ccbba6e60ae092cf4a705e636e32655#diff-04c6e90faac2675aa89e2176d2eec7d8R33

**Comment by Shougo** [comment]
Please read this.

https://github.com/zxqfl/TabNine/issues/106

It is not deoplete-tabnine's fault.
Other tabnine's clients cannot support the feature.

**Comment by tbodt** [comment]
Apparently it is possible based on the response to zxqfl/TabNine#106.

**Comment by Shougo** [comment]
I get it.
deoplete support is needed for the feature.

**Comment by Shougo** [comment]
Please wait.   I will add the support.

**Comment by Shougo** [comment]
@dkvasnicka Please test #31.

**Comment by dkvasnicka** [comment]
I've updated Deoplete and switched to the `shougo/suffix` branch for this plugin but I see no change. Whenever the completion is like `object.method(` or `object.method("` nothing gets closed when I press enter to select the completion option (note that you need to be able to close multiple nested pairs, like a paren and a quote -- but not even simple paren closing works). Anything I should check out?

I would much rather see TabNine itself to completely remove this partial completion pseudofeature, I don't even understand why they are doing this. But seems like they don't perceive this as a problem...

**Comment by dkvasnicka** [comment]
Ah, sorry, works! I switched to the fix branch but then I did Plug update to get the new Deoplete and it silently switched me back to `master`.
Works like a charm!
