### ISSUE TITLE
Cannot verify if it is working

### ISSUE THREAD

**Issue by owang** [tbodt/deoplete-tabnine#34]
I followed the installation instructions, but don't see TabNine completion results in my deoplete list. Is there a way to check the install or debug what is going on? Typing `TabNine::version` in a new buffer does nothing, although I am not sure if that is expected to work or not.

**Comment by Shougo** [comment]
If it does nothing, Tabnine doesn't work.
You can check tabnine process in process manager.

**Comment by Shougo** [comment]
You should create the minimal environment.

**Comment by owang** [comment]
This is my minimal nvim config:
```
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

if has('win32') || has('win64')
  Plug 'tbodt/deoplete-tabnine', { 'do': 'powershell.exe .\install.ps1' }
else
  Plug 'tbodt/deoplete-tabnine', { 'do': './install.sh' }
endif

call plug#end()

call deoplete#custom#var('tabnine', {
\ 'line_limit': 500,
\ 'max_num_results': 20,
\ })
```

PlugStatus shows both plugins working fine:

```
Finished. 0 error(s)
[==]                                                                                                                                      
- deoplete.nvim: OK
- deoplete-tabnine: OK
```

Typing `TabNine::version` has no output

Thanks!

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L325
g:deoplete#enable_at_startup is needed.

**Comment by owang** [comment]
Ah right, this was missed in my minimum working example case. But great, it works now, although still not in my real config. But now I can go and turn things on until it stops working. Thanks!
