### ISSUE TITLE
Unhandled exception (Error)

### ISSUE THREAD

**Issue by hissssst** [tbodt/deoplete-tabnine#35]
![image](https://user-images.githubusercontent.com/37012324/63675957-9f4ac000-c7f2-11e9-9119-379fe1884151.png)

**Comment by Shougo** [comment]
Your tabnine binary is too old.
Please update it by `./install.sh` in repository directory.

**Comment by Shougo** [comment]
https://github.com/tbodt/deoplete-tabnine/issues/36

It seems same error.

**Comment by hissssst** [comment]
Didn't occur anymore

**Comment by Shougo** [comment]
Yes.  I have fixed it in PR.
