### ISSUE TITLE
Error when pressing backspace after complete

### ISSUE THREAD

**Issue by kimusan** [tbodt/deoplete-tabnine#36]
Hi I see the error in the screenshot when I do TabNine::config and then press backspace after finalizing the complete
 
![Screenshot from 2019-08-26 20-32-57](https://user-images.githubusercontent.com/1150049/63713978-042d0700-c841-11e9-9e7c-2917b66fc9e1.png)

I get it every time. The TabNine is installed minutes ago and I did run the ./install.sh

**Comment by Shougo** [comment]
It seems TabNine's problem.
TabNine's output is corrupt.

Please ask it in TabNine's issue.

**Comment by Shougo** [comment]
I have tested TabNine 2.1.13.
It works.  What is your TabNine version?
