### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by hissssst** [tbodt/deoplete-tabnine#39]
![2019-10-14-191157_1920x1056_scrot](https://user-images.githubusercontent.com/37012324/66766356-943d1380-eeb6-11e9-8955-007063adb0a6.png)
Four nvim instances kill my memory. It used to be fine
One instance uses **twice** as much as 10 firefox tabs usage

**Comment by tbodt** [comment]
Not a problem with the vim plugin, open an issue at https://github.com/zxqfl/TabNine.

**Comment by hissssst** [comment]
Actually, you could share the `TabNine` between the vim instances without spawning it for every vim instance.

**Comment by hissssst** [comment]
You may reopen the issue, so I may write a pr

**Comment by tbodt** [comment]
I don't think TabNine is designed to allow sharing between editor instances. How do you plan to do it?

**Comment by hissssst** [comment]
@tbodt . I thought about it via piping `TabNine`'s `stdin/stdout` to some files somewhere in `/tmp`.
You can't type into two different nvim instances simultaneously, so it is possible to time-track different answers to different requests.
This implementation has some problems like suggestions from one editor will be shown in the other editor, but i think it's ok, because the same thing happens when switching between different splits in one instance

**Comment by tbodt** [comment]
It is possible for two people to type in two nvim instances simultaneously, which is less OK. You should request multi-user support from upstream first.

**Comment by hissssst** [comment]
@tbodt Okay, you're right. I'll ask tabnine for support
