### ISSUE TITLE
Errors with Python 3.5

### ISSUE THREAD

**Issue by kpine** [tbodt/deoplete-tabnine#4]
Python errors occur when trying to use this in Python 3.5.

The `encoding` argument for `subprocess.Popen` was added in Python 3.6, thus using it in 3.5 causes an error. Removing the encoding parameter from `Popen` solves that particular error, but the stdin/stdout/stderr file objects are then opened in binary mode instead of text mode, so you run into errors later on when strings are used (want bytes). My quick workaround was to use `Popen` with the `universal_newlines=True` argument instead, which exists in 3.5 and causes the file objects to be opened in text mode (same as when `encoding` is used). After that I have not seen any errors and completion is working.

I'm using Debian 9 which only includes Python 3.5. Deoplete also only requires a minimum of Python 3.5, so it would be nice if this also supported 3.5+ as well. If not, perhaps a note about the minimum requirements would be helpful.

**Comment by tbodt** [comment]
universal_newlines could mess up the newline translation on Windows, where I think `\n` is required. The solution used in the Sublime plugin is to use .decode and .encode.
