### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by hissssst** [tbodt/deoplete-tabnine#41]
Back again from #39 

I've tried `coc-tabnine` just to compare, and coc's version uses 7 times less memory compared to deoplete's one. I think the difference exists because coc uses **VSCode** version of tabnine and deoplete uses **sublime** version.

**Comment by Shougo** [comment]
Really?   Please upload the memory usage.

**Comment by Shougo** [comment]
https://github.com/tbodt/deoplete-tabnine/pull/42

I have changed it to use vscode client.  Please test it.

**Comment by hissssst** [comment]
The issue was not in client type, closing
