### ISSUE TITLE
not deoplete-tabnine/binaries path

### ISSUE THREAD

**Issue by jclivi** [tbodt/deoplete-tabnine#44]
.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 186, i..
.e: [Errno 2] No such file or directory: '.vim/bundle/deoplete-tabnine/binaries'.  Use :messages / see above for error details.^@

**Comment by BillGR17** [comment]
The servers are down i think...
The script right now its downloading the 403 webpage and marks it as executable
EDIT: by script i mean the install.sh

**Comment by amircodota** [comment]
Seems to work correctly for me, on ubuntu 18.04.

Can you run 

uname -s

and

uname -m

and see what they return on your machine?

Thanks
Amir

**Comment by BillGR17** [comment]
uname -s Linux
uname -m armv7l

**Comment by Shougo** [comment]
`./install.sh` seems work for me.

**Comment by amircodota** [comment]
I'm afraid TabNine does not support arm currently.

What type of device are you using?

**Comment by Shougo** [comment]
Oh, Tabnine doesn't support ARM architecture.

**Comment by BillGR17** [comment]
Damn. I have a tinkerboard (its like a raspberry pi). Its not my main device but i do some coding there from time to time.

**Comment by tbodt** [comment]
Closing as this isn't an issue with deoplete-tabnine
