### ISSUE TITLE
Offline completion

### ISSUE THREAD

**Issue by rjshrjndrn** [tbodt/deoplete-tabnine#48]
Hi,
Thanks for the tabnine support. One question is, tabnine support offline completion. Is there any way to mandate that in plugin ?

**Comment by Shougo** [comment]
> One question is, tabnine support offline completion.

Tabnine local?

Please use `TabNine::config`.

**Comment by rjshrjndrn** [comment]
Sorry for being a noob, I didn't quite get you. @Shougo

**Comment by Shougo** [comment]
Sorry.  I don't understand your question

**Comment by rjshrjndrn** [comment]
Tabnine has a completion option for offline completion. https://www.tabnine.com/subscribe/
So is there a way to add the configuration or flag to enable that

**Comment by Shougo** [comment]
Hm.  It is enabled on default.
You can use Tabnine in offline environment.

**Comment by rjshrjndrn** [comment]
means tabnine will never use internet ? 
Thanks :)

**Comment by Shougo** [comment]
Tabnine doesn't require Internet

**Comment by rjshrjndrn** [comment]
Wooho.. that's what I was looking for. Because sometimes my completion was becoming sluggish, kind of slow. Thanks for clarifying it.

**Comment by Shougo** [comment]
If the completion is slow, you should use powerful machine or disable Tabnine local feature.
