### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by notKamui** [tbodt/deoplete-tabnine#49]
Hi ! When starting neovim, and going into Insert mode, I get the following error.
I tried to find the right permissions, to no avail.

I'm on Arch Linux, if that may help.

![2020 09 07-19 55 33 screenshot](https://user-images.githubusercontent.com/46132319/92410436-57b87d00-f144-11ea-9b9c-4bfe88b3e1b3.png)

Sorry for the inconvenience :(

**Comment by Shougo** [comment]
Really?
I don't think it has the right permission.

**Comment by Shougo** [comment]
Please upload the permission.
And execute it from shell.

**Comment by notKamui** [comment]
```
$ lart .local/share/nvim/plugged/deoplete-tabnine/binaries/3.0.7/x86_64-unknown-linux-gnu/
total 14772
drwxr-x--- 3 notkamui notkamui     4096 Sep  7 21:41 ..
drwxr-x--- 2 notkamui notkamui     4096 Sep  7 21:41 .
-rw-r--r-- 1 notkamui notkamui 15118282 Sep  7 21:49 TabNine
```

**Comment by notKamui** [comment]
btw, i tried reinstalling it, and it made me remember that at the end of it, there was a post process hook error.

**Comment by Shougo** [comment]
> btw, i tried reinstalling it, and it made me remember that at the end of it, there was a post process hook error.

I don't understand.  Please explain it more clearly.

> -rw-r--r-- 1 notkamui notkamui 15118282 Sep  7 21:49 TabNine

Ah...

You need to add execute permission to the TabNine binary.
Please look my result.

```
$ ls -la binaries/3.0.7/x86_64-unknown-linux-gnu
total 15180
drwxr-xr-x 2 shougo users     4096 Sep  4 19:33 ./
drwxr-xr-x 3 shougo users     4096 Sep  4 19:33 ../
-rw-r--r-- 1 shougo users       64 Sep  4 19:33 auth
-rwxr-xr-x 1 shougo users 15529960 Sep  4 19:33 TabNine*
```

**Comment by Shougo** [comment]
The issue should be closed.

**Comment by tbodt** [comment]
Whatever the problem is most likely happened during the installation process. Please open a new issue if you can reproduce that.
