### ISSUE TITLE
Excessive cpu/memory usage

### ISSUE THREAD

**Issue by petobens** [tbodt/deoplete-tabnine#50]
@Shougo conside the following minimal init.vim file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/deoplete.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/tbodt/deoplete-tabnine
filetype plugin indent on

let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('tabnine', 'rank', 101)
```
Now as in the GIF:
i) Open neovim and something to monitor cpu usage (such as `htop`)
ii) Within neovim open a markdown file (such as `foo.md`) and start writing some text (such as `# Foo`))
After ii) you will see that CPU/memory increases enormously. Is there a way to limit the number of process being spawned? 

![deoplete-tabnine](https://user-images.githubusercontent.com/2583971/95697680-e0c84580-0c15-11eb-81f8-2a1b1656b7d5.gif)

For the record i installed tabnine with:
```
call dein#add('tbodt/deoplete-tabnine', {'build': './install.sh'})
```
which results in version 3.1.6

**Comment by Shougo** [comment]
It is the Tabnine feature.

Please read Tabnine issues.
https://github.com/codota/TabNine/issues

You can see many of several issues.

Note: You can disable TabNine local feature by `TabNine::config`.

**Comment by petobens** [comment]
> Note: You can disable TabNine local feature by TabNine::config

How can I do this? Is there a deoplete setting for that?

**Comment by Shougo** [comment]
Please input it in Vim buffer.
It is Tabnine feature.

**Comment by petobens** [comment]
Oh I see. I doesn't change memory usage a lot though. Do you use tabnine?

**Comment by Shougo** [comment]
Yes.  I use it.  It uses a lot of CPU usage...
Powerful computer is suggested.

**Comment by petobens** [comment]
Ok. Thanks. Feel free to close.

**Comment by Shougo** [comment]
@tbodt Ping.
