### ISSUE TITLE
Neovim freez when using TabNine

### ISSUE THREAD

**Issue by tzachar** [tbodt/deoplete-tabnine#51]
Hi.

Been using TabNine for a long while.
Lately (neovim nightly), neovim started freezing, mostly when closing or switching buffers.
The main nevom process is hanged on an epoll from the TabNine client, and killing the TabNine process unfreezes everything.

Is this a know issue?
Is there a workaround?

**Comment by Shougo** [comment]
Unfortunately, it is TabNine's problem...

**Comment by tzachar** [comment]
Ok, but I think we can better interact with the process.
Dumping the request as json directly to the process's stdin and directly reading from its stdout is probably not robust. 
A better option would be to use non blocking reads, like the attached patch.
I'll report if the patch helps.


[p.txt](https://github.com/tbodt/deoplete-tabnine/files/5457801/p.txt)

**Comment by Shougo** [comment]
Please send the PR.  I will test it.

**Comment by Shougo** [comment]
Hm.  If edit huge buffer, tabnine process is very busy.
I will add the option for it.

**Comment by Shougo** [comment]
@tzachar The issue should be closed.

**Comment by tzachar** [comment]
right.
