### ISSUE TITLE
linux-musl support

### ISSUE THREAD

**Issue by amircodota** [tbodt/deoplete-tabnine#54]
Hi, 

Amir from Codota (the company behind TabNine) here.

I see this plugin has moved from linux-gnu to linux-musl a long time ago ([here](https://github.com/tbodt/deoplete-tabnine/commit/4e15048ff45806100fd1a4ee2dfdf9a28029da40)), but recently reverted back to linux-gnu ([here](https://github.com/tbodt/deoplete-tabnine/commit/3d69c2fa24f98b4bc7491cf144c46db13aa4f5b6)).

I was wondering what was the reason for reverting back?

Thanks

**Comment by tbodt** [comment]
@tzachar

**Comment by Shougo** [comment]
I don't know the difference.
Which is the better for deoplete-tabnine?

**Comment by tzachar** [comment]
Im not sure. I think it was the version which worked best for me at
that time.

What exactly is the difference? Can you explain?

**Comment by amircodota** [comment]
Basically [musl](https://musl.libc.org/about.html) and gnu are 2 different libc implementations.

While both would work fine the vast majority of times, we did see situations where gnu (also known as glibc) failed to find some dependencies while musl worked fine. Personally, I saw it mostly on docker containers where the images were very minimal, but I guess it could happen in other instances too.

So we prefer the musl version for linux, but also keep the gnu version for backwards compatibility.

Maybe @zxqfl can also share form his experience.

**Comment by Shougo** [comment]
OK.  So musl is better.

**Comment by amircodota** [comment]
@Shougo Yes, as far as we know. 
@tzachar if you can remember what was the issue that caused you to revert, we might be able to look into it

**Comment by tzachar** [comment]
Sorry, I dont remember.

**Comment by Shougo** [comment]
I have create the fix for it.
