### ISSUE TITLE
The binary package for aarch64

### ISSUE THREAD

**Issue by lee-shun** [tbodt/deoplete-tabnine#62]
Hi, there;

These days  I prepare to use the deoplete-tabnie on TX2(Nvidia develop board), which is aarch64 architecture.

Would you please add the aarch64 Linux support? 

Thanks a lot!

**Comment by Shougo** [comment]
Currently, `"$(uname -m)-unknown-linux-musl"` binary is downloaded.
What is your `uname -a` result?
But `aarch64-unknown-linux-musl` binary is not distributed.

https://github.com/codota/TabNine/issues/282
https://github.com/codota/TabNine/issues/65

It is not issue of deoplete-tabnine.

It should be closed...

**Comment by lee-shun** [comment]
Thank you for your quick reply! I see .....

**Comment by lee-shun** [comment]
It is not an issue of deoplete-tabnine.
